### ISSUE TITLE
tree.getById(id) how to get by id?

### ISSUE THREAD

**Issue by hoogw** [mourner/rbush#105] opened 2020-05-07 17:11 UTC
Is there function I can get by id?

How to return item by id?

        For example I insert 2 item, with id field 1, 2
    `const item = {
    minX: 20,
    minY: 40,
    maxX: 30,
    maxY: 50,
    id: 1
    };

    const item2= {
    minX: 10,
    minY: 20,
    maxX: 20,
    maxY: 30,
    id: 2
    };

    tree.insert(item);
    tree.insert(item2);`

Now, I want get the item by id only.

            `const result = tree.getByID(2);`
 
Then I get item return as item2, because its id is 2.

**Comment by photonstorm** [comment] 2020-05-07 19:01
There isn’t, because that’s not what an RTree does. Perhaps this isn’t the right sort of data structure you’re looking for?

**Comment by IvanSanchez** [comment] 2020-05-07 20:55
Duplicate of #104.

**Closed** 2020-05-08 13:19 UTC
