### ISSUE TITLE
Typescript attempts to use missing default constructor

### ISSUE THREAD

**Issue by YarekTyshchenko** [mourner/rbush#113] opened 2020-10-30 11:34 UTC
Are typescript typings up to date?

```
new rbush_1.default();
^

TypeError: rbush_1.default is not a constructor
```
on file:
```typescript
import RBush from "rbush";
new RBush()
```
with tsconfig settings:
```tsconfig.json
{
    "compilerOptions": {
        "lib": ["es2018"],
        "module": "commonjs",
        "target": "es2018"
    }
}
```
This is just installing with `yarn add rbush @types/rbush` which gives me `@types/rbush 3.0.0`, and `rbush 3.0.1`

**Comment by IvanSanchez** [comment] 2020-10-30 12:14
Typescript defs for rbush are handled at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/rbush , not here.

**Comment by YarekTyshchenko** [comment] 2020-10-30 13:25
I'm afraid I don't have a clue how to update the typings. Playing around with versions, it seems the current typings seem to work with `2.0.2` release of Rbush, so that must be it

**Comment by IvanSanchez** [comment] 2020-10-30 14:09
I suggest closing as a duplicate of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39315

**Comment by mourner** [comment] 2020-10-30 15:29
Yeah, I don't use TypeScript and the typings are third-party so I can't really help here. My guess is that it has to do with `module": "commonjs"` in TS options.

**Closed by mourner** 2020-10-30 15:29 UTC
Labels: question
